#!/usr/bin/env python3
"""
Snapshot composer_venues_v2.image_keys to CSV before a wipe-and-replace import.

Output: docs/debug/image_keys_snapshot_<timestamp>.csv
Format: google_place_id,image_keys (image_keys as JSON-encoded array)

Why google_place_id (not venue_id): venue_id may be regenerated by the
importer; google_place_id is canonical and stable.
"""

from __future__ import annotations
import csv
import json
import os
import sys
from datetime import datetime, timezone


def load_env():
    env_file = os.path.join(os.path.dirname(__file__), "..", ".env.local")
    if os.path.exists(env_file):
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    os.environ.setdefault(key.strip(), val.strip().strip('"'))


def get_supabase():
    try:
        from supabase import create_client
        return create_client(
            os.environ["NEXT_PUBLIC_SUPABASE_URL"],
            os.environ["SUPABASE_SERVICE_ROLE_KEY"],
        )
    except ImportError:
        print("ERROR: supabase-py not installed. Run: pip3 install supabase")
        sys.exit(1)


def main():
    load_env()
    supabase = get_supabase()

    # Page through every row — Supabase default page is 1000
    all_rows = []
    page_size = 1000
    offset = 0
    while True:
        res = supabase.table("composer_venues_v2") \
            .select("google_place_id, image_keys") \
            .range(offset, offset + page_size - 1) \
            .execute()
        rows = res.data
        if not rows:
            break
        all_rows.extend(rows)
        if len(rows) < page_size:
            break
        offset += page_size

    print(f"Fetched {len(all_rows)} rows from composer_venues_v2")

    # Filter to rows with both fields populated
    snapshot = [
        (r["google_place_id"], r["image_keys"])
        for r in all_rows
        if r.get("google_place_id") and r.get("image_keys")
    ]
    print(f"  with both google_place_id and non-empty image_keys: {len(snapshot)}")

    # Write CSV
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out_dir = os.path.join(os.path.dirname(__file__), "..", "docs", "debug")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"image_keys_snapshot_{timestamp}.csv")

    with open(out_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["google_place_id", "image_keys"])
        for gpid, keys in snapshot:
            writer.writerow([gpid, json.dumps(keys)])

    print(f"\nSnapshot written: {out_path}")
    print(f"Rows: {len(snapshot)}")
    print(f"\nKeep this file. The restore step (Step 5) reads it back.")


if __name__ == "__main__":
    main()
