// POST /api/daily-pick — Tonight's Pick handler. Lazy per-user, per-day
// cache for a seeded itinerary, generated by calling /api/generate
// UNCHANGED. No new generation path: this route orchestrates a cache
// check + a single internal generate call.
//
// Flow:
//   1. Auth the user (cookie session). Logged-out → 401, client treats
//      as "no pick today" and renders nothing.
//   2. Compute today's local NYC date.
//   3. SELECT from composer_daily_picks WHERE (user_id, pick_date).
//      Hit → return cached payload + was_first_view flag.
//   4. Miss → seeded roll (rollLuckyInputsSeeded with seed source
//      `${user_id}|${pick_date}`), call /api/generate with mode="daily"
//      and excludeVenueIds=[] (server-side; we don't pass the user's
//      recent-exclusions because Tonight's Pick is deterministic per
//      day — varying excludes by view time would break that).
//   5. On success: INSERT { status:'ready', inputs, itinerary,
//      first_viewed_at: NOW() } and return with was_first_view=true.
//      On 422 across all LUCKY.maxAttempts retries: INSERT
//      { status:'failed', first_viewed_at: NOW() } and return null
//      payload — the client renders nothing.
//
// Architectural rule (non-negotiable per the spec): inputs only, strict
// /api/generate unchanged, no new generation path. The route does NOT
// call markComposeEntry, does NOT set the compose-abandoned flag, does
// NOT emit compose_started, does NOT emit compose_submitted (the
// internal generate call's server-side events carry mode="daily" via
// the body propagation in /api/generate).

import { NextResponse } from "next/server";
import { POST as generatePOST } from "@/app/api/generate/route";
import { getServerSupabase } from "@/lib/supabase/server";
import { getServiceSupabase } from "@/lib/supabase";
import {
  nextEligibleStartTime,
  rollLuckyInputsSeeded,
  isoDateToday,
} from "@/lib/lucky";
import { LUCKY } from "@/config/lucky";
import { isComposeFailure } from "@/lib/itinerary/compose-failure";
import type { GenerateRequestBody, ItineraryResponse } from "@/types";

interface ReadyResponse {
  status: "ready";
  inputs: GenerateRequestBody;
  itinerary: ItineraryResponse;
  pick_date: string;
  was_first_view: boolean;
}
interface FailedResponse {
  status: "failed";
  pick_date: string;
  was_first_view: boolean;
}
export type DailyPickResponse = ReadyResponse | FailedResponse;

/** Postgres unique-violation error code. Used by the race-loss
 *  recovery on both the success-write and the failed-tombstone paths
 *  so concurrent requests from the same user don't return divergent
 *  status values. */
const PG_UNIQUE_VIOLATION = "23505";

export async function POST(request: Request) {
  try {
    const supabase = await getServerSupabase();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Not signed in" }, { status: 401 });
    }

    // Today's local NYC date. Same isoDateToday the seeded roller uses
    // so the (seed source = user_id|pick_date) and (cache key) agree
    // exactly. Cron-edge cases (midnight tick during the request) are
    // ignored: at most one stale fetch.
    const now = new Date();
    const pickDate = isoDateToday(now);
    const service = getServiceSupabase();

    // ─── Step 1: cache lookup ─────────────────────────────────────
    const { data: existing, error: readErr } = await service
      .from("composer_daily_picks")
      .select("status, inputs, itinerary, first_viewed_at")
      .eq("user_id", user.id)
      .eq("pick_date", pickDate)
      .maybeSingle();
    if (readErr) {
      console.error("[daily-pick] cache read failed:", readErr.message);
      return NextResponse.json({ error: "Read failed" }, { status: 500 });
    }
    if (existing) {
      // Hit. The "first view today" decision MUST come from the
      // conditional UPDATE's affected-rows — NOT from the SELECT. Two
      // tabs racing the SELECT would both see first_viewed_at=null and
      // both return was_first_view=true if we trusted the SELECT,
      // double-firing daily_pick_viewed (spec demands once per
      // (user, date)). The conditional UPDATE serializes: at most one
      // request gets affected_rows=1; the loser gets 0 and reports
      // was_first_view=false.
      let wasFirstView = false;
      if (existing.first_viewed_at === null) {
        const { data: stamped, error: stampErr } = await service
          .from("composer_daily_picks")
          .update({ first_viewed_at: new Date().toISOString() })
          .eq("user_id", user.id)
          .eq("pick_date", pickDate)
          .is("first_viewed_at", null)
          // .select() returns the rows the UPDATE actually modified.
          // Postgres + the `.is` predicate guarantee at most one row
          // is updated across concurrent calls.
          .select("user_id");
        if (stampErr) {
          console.error(
            "[daily-pick] first_viewed_at stamp failed:",
            stampErr.message,
          );
          // Don't fail the request on stamp errors — at worst the
          // client emits no impression for this view; the next view
          // will retry the stamp.
        } else {
          wasFirstView = (stamped?.length ?? 0) === 1;
        }
      }
      return NextResponse.json(
        existing.status === "ready"
          ? {
              status: "ready",
              inputs: existing.inputs as GenerateRequestBody,
              itinerary: existing.itinerary as ItineraryResponse,
              pick_date: pickDate,
              was_first_view: wasFirstView,
            }
          : {
              status: "failed",
              pick_date: pickDate,
              was_first_view: wasFirstView,
            },
      );
    }

    // ─── Step 2: cache miss → seeded generation ───────────────────
    const startTime = nextEligibleStartTime(now);
    if (!startTime) {
      // Past the same-day cutoff — no honest pick possible today.
      // Tombstone so we don't re-roll on every refresh. Race-recovery
      // matches the success path: if a concurrent winner already wrote
      // the row (any status), return their payload with
      // was_first_view=false instead of a divergent reply.
      return NextResponse.json(
        await writeFailedTombstone(service, user.id, pickDate),
      );
    }

    const seedSource = `${user.id}|${pickDate}`;
    let success: { inputs: GenerateRequestBody; itinerary: ItineraryResponse } | null =
      null;

    for (let attempt = 1; attempt <= LUCKY.maxAttempts; attempt++) {
      const roll = rollLuckyInputsSeeded(now, startTime, seedSource, attempt);
      // Internal call to the unchanged /api/generate handler. The
      // request carries the user's cookies via the forwarded headers,
      // so getServerSupabase() inside /api/generate sees the same auth
      // context. excludeVenueIds is [] — Tonight's Pick is meant to be
      // deterministic per day; varying the exclusion set by view time
      // would defeat the seed.
      const generateReq = new Request("http://internal/api/generate", {
        method: "POST",
        headers: request.headers,
        body: JSON.stringify({
          ...roll.body,
          mode: "daily",
          excludeVenueIds: [],
        }),
      });
      const res = await generatePOST(generateReq);
      if (res.status === 200) {
        const itinerary = (await res.json()) as ItineraryResponse;
        success = { inputs: roll.body, itinerary };
        break;
      }
      if (res.status === 422) {
        // Sanity check the failure shape; on success it would have hit
        // the 200 branch above. Continue the attempt loop.
        const body = (await res.json().catch(() => ({}))) as unknown;
        if (!isComposeFailure(body)) {
          // Malformed 422 — treat as exhaustion, don't keep retrying.
          break;
        }
        continue;
      }
      // 500-class — exit, don't burn more compute on rerolls.
      console.error(
        `[daily-pick] /api/generate status ${res.status}; aborting retries`,
      );
      break;
    }

    if (success) {
      const { error: writeErr } = await service
        .from("composer_daily_picks")
        .insert({
          user_id: user.id,
          pick_date: pickDate,
          status: "ready",
          inputs: success.inputs,
          itinerary: success.itinerary,
          first_viewed_at: new Date().toISOString(),
        });
      if (writeErr) {
        console.error("[daily-pick] cache write failed:", writeErr.message);
        // Race-loss path: a concurrent request from the same user beat
        // us to the insert (PG_UNIQUE_VIOLATION). Read whichever status
        // the winner wrote and return their payload with
        // was_first_view=false.
        if (writeErr.code === PG_UNIQUE_VIOLATION) {
          const { data: late } = await service
            .from("composer_daily_picks")
            .select("status, inputs, itinerary, first_viewed_at")
            .eq("user_id", user.id)
            .eq("pick_date", pickDate)
            .maybeSingle();
          if (late?.status === "ready") {
            return NextResponse.json({
              status: "ready",
              inputs: late.inputs as GenerateRequestBody,
              itinerary: late.itinerary as ItineraryResponse,
              pick_date: pickDate,
              was_first_view: false,
            });
          }
          if (late?.status === "failed") {
            return NextResponse.json({
              status: "failed",
              pick_date: pickDate,
              was_first_view: false,
            });
          }
        }
        return NextResponse.json({ error: "Write failed" }, { status: 500 });
      }
      return NextResponse.json({
        status: "ready",
        inputs: success.inputs,
        itinerary: success.itinerary,
        pick_date: pickDate,
        was_first_view: true,
      });
    }

    // All attempts exhausted on 422 → tombstone (with race recovery).
    return NextResponse.json(
      await writeFailedTombstone(service, user.id, pickDate),
    );
  } catch (err) {
    console.error("[daily-pick] error:", err);
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}

/** Insert a status='failed' tombstone for (user, pick_date). On
 *  unique-violation (concurrent winner already wrote the row, possibly
 *  with status='ready'), re-read the canonical row and return its
 *  payload with was_first_view=false. Symmetric to the success path's
 *  race-loss recovery so concurrent callers in different branches
 *  (e.g. one hit the cutoff while another succeeded on 200) don't
 *  return divergent status values for the same (user, date). */
async function writeFailedTombstone(
  service: ReturnType<typeof getServiceSupabase>,
  userId: string,
  pickDate: string,
): Promise<DailyPickResponse> {
  const { error } = await service.from("composer_daily_picks").insert({
    user_id: userId,
    pick_date: pickDate,
    status: "failed",
    first_viewed_at: new Date().toISOString(),
  });
  if (!error) {
    return { status: "failed", pick_date: pickDate, was_first_view: true };
  }
  if (error.code === PG_UNIQUE_VIOLATION) {
    // A concurrent request beat us to the row. Read it back so this
    // caller sees the winner's status instead of a stale 'failed'.
    const { data: winner } = await service
      .from("composer_daily_picks")
      .select("status, inputs, itinerary")
      .eq("user_id", userId)
      .eq("pick_date", pickDate)
      .maybeSingle();
    if (winner?.status === "ready") {
      return {
        status: "ready",
        inputs: winner.inputs as GenerateRequestBody,
        itinerary: winner.itinerary as ItineraryResponse,
        pick_date: pickDate,
        was_first_view: false,
      };
    }
    return { status: "failed", pick_date: pickDate, was_first_view: false };
  }
  // Non-unique-violation error — best-effort: log and return a failed
  // status. The next view will re-attempt (no cache row exists).
  console.error("[daily-pick] tombstone insert failed:", error.message);
  return { status: "failed", pick_date: pickDate, was_first_view: true };
}
